use_frameworks!

platform :ios, '13.0'

target 'ModuleCore_Example' do
  pod 'ModuleCore', :path => '../'

  target 'ModuleCore_Tests' do
    inherit! :search_paths

#    pod 'Nimble', '~> 10.0.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
